name: Deploy to RapidAPI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      # Get spec files that have changed
      - name: Get specific changed files
        id: changed-spec-files
        uses: tj-actions/changed-files@v16
        with:
          files: |
            *.json

      # print list of files for debug purposes
      - name: List updated spec files
        run: |
          for file in ${{ steps.changed-spec-files.outputs.modified_files }}; do
            echo "$file was modified"
          done    
          
      # POST to Integration Service
      - name: Post to Integration Layer
        id: postToIntegrationLayer
        if: steps.changed-spec-files.outputs.any_changed == 'true'
        # You may pin to the exact commit or the version.
        # uses: fjogeleit/http-request-action@d45f6649f63b711b64bcd10e95a600abe4468456
        uses: fjogeleit/http-request-action@v1.9.0
        with:
          url: https://ed5u76i86j.execute-api.us-east-1.amazonaws.com/prod/github
          customHeaders: '{"instance" : "jeff"}'
          method: POST
          contentType: "application/json"
          file: ${{ steps.changed-spec-files.outputs.modified_files }}

      - name: Show Response
        run: echo ${{ steps.postToIntegrationLayer.outputs.response }}   
